[tool.poetry]
name = "kofferpackentrainer"
version = "0.1.0"
description = ""
authors = ["Ma173 <malte.gerhardt@rub.de>"]

[tool.poetry.dependencies]
python = "^3.7"
dicttoxml = "^1.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
